[Prod]
hosts =
    srv1-p
    8.8.8.8
[Prod.Domain_Controllers]
hosts =
    ad1-p
    ad2-p
    ad3-p

[Prod.DHCP_Servers]
hosts =
    dhcp1-p

[Test]
hosts =
    srv1-t

[Prod.Infrastructure]
hosts =
    srv2-p
    srv3-p
    
